#ifndef PLUGINSETTINGSEXPORT_H
#define PLUGINSETTINGSEXPORT_H

#ifdef PLUGINSETTINGS_MAKE_LIBRARY
	#define PLUGINSETTINGS_EXPORT Q_DECL_EXPORT
#else
	#define PLUGINSETTINGS_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINSETTINGSEXPORT_H
