#ifndef PLUGINEDITOREXPORT_H
#define PLUGINEDITOREXPORT_H

#ifdef PLUGINEDITOR_MAKE_LIBRARY
	#define PLUGINEDITOR_EXPORT Q_DECL_EXPORT
#else
	#define PLUGINEDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINEDITOREXPORT_H
