#ifndef PLUGINPROJECTEXPLOREREXPORT_H
#define PLUGINPROJECTEXPLOREREXPORT_H

#ifdef PLUGINPROJECTEXPLORER_MAKE_LIBRARY
	#define PLUGINPROJECTEXPLORER_EXPORT Q_DECL_EXPORT
#else
	#define PLUGINPROJECTEXPLORER_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINPROJECTEXPLOREREXPORT_H
