#ifndef PLUGINPROJECTEXPLOREREXPORT_H
#define PLUGINPROJECTEXPLOREREXPORT_H

#ifdef PLUGINPROJECTS_EXPORT
	#define PLUGINPROJECTEXPLORER_API Q_DECL_EXPORT
#else
	#define PLUGINPROJECTEXPLORER_API Q_DECL_IMPORT
#endif

#endif // PLUGINPROJECTEXPLOREREXPORT_H
