#ifndef PLUGINTOOLCHAINEXPORT_H
#define PLUGINTOOLCHAINEXPORT_H

#ifdef PLUGINTOOLCHAIN_MAKE_LIBRARY
	#define PLUGINTOOLCHAIN_EXPORT Q_DECL_EXPORT
#else
	#define PLUGINTOOLCHAIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINTOOLCHAINEXPORT_H
