#ifndef PLATFORMEXPORT_H
#define PLATFORMEXPORT_H

#ifdef CDEVSTUDIOPLATFORM_MAKE_LIBRARY
	#define CDEVSTUDIOPLATFORM_EXPORT Q_DECL_EXPORT
#else
	#define CDEVSTUDIOPLATFORM_EXPORT Q_DECL_IMPORT
#endif

#endif // PLATFORMEXPORT_H
