#ifndef PLUGINPROJECTSEXPORT_H
#define PLUGINPROJECTSEXPORT_H

#ifdef PLUGINPROJECTS_MAKE_LIBRARY
	#define PLUGINPROJECTS_EXPORT Q_DECL_EXPORT
#else
	#define PLUGINPROJECTS_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINPROJECTSEXPORT_H
