#ifndef PLUGINPROJECTSEXPORT_H
#define PLUGINPROJECTSEXPORT_H

#ifdef PLUGINPROJECTS_EXPORT
	#define PLUGINPROJECTS_API Q_DECL_EXPORT
#else
	#define PLUGINPROJECTS_API Q_DECL_IMPORT
#endif

#endif // PLUGINPROJECTSEXPORT_H
