#ifndef PLUGINPROJECTWIZARDEXPORT_H
#define PLUGINPROJECTWIZARDEXPORT_H

#ifdef PLUGINPROJECTWIZARD_MAKE_LIBRARY
	#define PLUGINPROJECTWIZARD_EXPORT Q_DECL_EXPORT
#else
	#define PLUGINPROJECTWIZARD_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINPROJECTWIZARDEXPORT_H
