#ifndef PLUGINPROJECTDATAEXPORT_H
#define PLUGINPROJECTDATAEXPORT_H

#ifdef PLUGINPROJECTDATA_MAKE_LIBRARY
	#define PLUGINPROJECTDATA_EXPORT Q_DECL_EXPORT
#else
	#define PLUGINPROJECTDATA_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINPROJECTDATAEXPORT_H
