#ifndef PLUGINPROJECTEXPORT_H
#define PLUGINPROJECTEXPORT_H

#ifdef PLUGINPROJECT_MAKE_LIBRARY
	#define PLUGINPROJECT_EXPORT Q_DECL_EXPORT
#else
	#define PLUGINPROJECT_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINPROJECTEXPORT_H
