#ifndef CDEVSTUDIOBACKENDEXPORT_H
#define CDEVSTUDIOBACKENDEXPORT_H

#ifdef CDEVSTUDIOBACKEND_EXPORT
	#define CDEVSTUDIOBACKEND_API Q_DECL_EXPORT
#else
	#define CDEVSTUDIOBACKEND_API Q_DECL_IMPORT
#endif

#endif // CDEVSTUDIOBACKENDEXPORT_H
