#ifndef PLUGINTEXTEDITOREXPORT_H
#define PLUGINTEXTEDITOREXPORT_H

#ifdef PLUGINTEXTEDITOR_MAKE_LIBRARY
	#define PLUGINTEXTEDITOR_EXPORT Q_DECL_EXPORT
#else
	#define PLUGINTEXTEDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINTEXTEDITOREXPORT_H
