#ifndef CDEVSTUDIOPLATFORMEXPORT_H
#define CDEVSTUDIOPLATFORMEXPORT_H

#ifdef CDEVSTUDIOPLATFORM_EXPORT
	#define CDEVSTUDIOPLATFORM_API Q_DECL_EXPORT
#else
	#define CDEVSTUDIOPLATFORM_API Q_DECL_IMPORT
#endif

#endif // CDEVSTUDIOPLATFORMEXPORT_H
